[phases.setup]
nixPkgs = ["python311", "nodejs"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["cd ui && npm install && npm run build"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
