[phases.setup]
nixPkgs = ["python311", "nodejs_24"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "cd ui && npm install && npm run build"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"

